# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ClickIPO' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ClickIPO

  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'GoogleIDFASupport'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'ClickIPOTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

